name: Reverse dependency testing
description: A GitHub Action to run tests of downstream packages
permissions:
  actions: read
  contents: read
  metadata: read
author: "Scientific-Python"
version: "1.0.0"

inputs:
  package_name:
    description: "Upstream package name used to create reverse dependency tree."
    required: true
  exclude:
    description: "List of packages to be excluded from testing."
    required: false
  include:
    description: |
      Whitelist of packages to be included in testing.
      When specified, `excluded` is ignored.'
      The resulting set of packages to be tested is an overlap between those
      in the dependency tree and those defined in `include`. If you want to
      define additional packages, use `additional`.
    required: false
  additional:
    description: |
      A list of additional packages not in the dependency tree to be tested.
      This is useful to test known downstream packages that have your package as
      an optional dependency hence will not show up in the dependency tree.
    required: false
  env:
    description: |
      Conda environment file to setup development environment allowing to build the package.
    required: false
  install:
    description: |
      Additional packages to be installed to the environment.
      These are not tested unless they are in the dependency tree anyway.
      You can pass a comma-separated list (e.g. "numpy,pandas,xarray").
    required: false
  installation_command:
    description: A command used to install the package from the repository
    required: false
    default: pip install .
  fail_on_failure:
    description: |
      Fail the action if there is a failure in any of the tests.
    required: false
    default: "true"
  run:
    description: Command to run prior doing anything else within the micromamba docker.
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
